name: New Issue
on: 
  issues:
    types:
      - opened

jobs:
  comment-on-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Issue comment
        uses: GrantBirki/comment@v2.0.10
        with:
          body: You've caused an issue!
